default:
    @just --list

watch:
    CARGO_PROFILE_DEV_OPT_LEVEL=0 \
    CARGO_PROFILE_DEV_CODEGEN_UNITS=16 \
    CARGO_PROFILE_DEV_DEBUG=false \
    CARGO_PROFILE_DEV_LTO=false \
    CARGO_TARGET_DIR=target/reload \
    cargo watch -w ui -d 0.01 -x "rustc --package ui --crate-type cdylib --profile dev --features reload"

run:
    cargo runcc -c runcc.yml
