default:
    @just --list

watch:
    CARGO_PROFILE_DEV_OPT_LEVEL=0 \
    CARGO_PROFILE_DEV_CODEGEN_UNITS=1 \
    CARGO_PROFILE_DEV_DEBUG=false \
    CARGO_PROFILE_DEV_LTO=false \
    CARGO_TARGET_DIR=target/reload \
    cargo watch -w src/ui -d 0.01 -x "rustc --package ui --crate-type cdylib --profile dev"


run:
    cargo run --release
